/**
 * Static dropdown options for form components
 * Centralized location for reusable select options
 */

import type { SelectOption } from "@/components/form"

// Gender options for profile forms
export const genderOptions: SelectOption[] = [
  { value: "male", label: "Male" },
  { value: "female", label: "Female" },
  { value: "other", label: "Other" },
  { value: "prefer_not_to_say", label: "Prefer not to say" }
]

// Country options with 2-letter ISO codes
export const countryOptions: SelectOption[] = [
  { value: "US", label: "United States" },
  { value: "CA", label: "Canada" },
  { value: "GB", label: "United Kingdom" },
  { value: "AU", label: "Australia" },
  { value: "DE", label: "Germany" },
  { value: "FR", label: "France" },
  { value: "IT", label: "Italy" },
  { value: "ES", label: "Spain" },
  { value: "NL", label: "Netherlands" },
  { value: "BE", label: "Belgium" },
  { value: "CH", label: "Switzerland" },
  { value: "AT", label: "Austria" },
  { value: "SE", label: "Sweden" },
  { value: "NO", label: "Norway" },
  { value: "DK", label: "Denmark" },
  { value: "FI", label: "Finland" },
  { value: "JP", label: "Japan" },
  { value: "KR", label: "South Korea" },
  { value: "CN", label: "China" },
  { value: "IN", label: "India" },
  { value: "SG", label: "Singapore" },
  { value: "HK", label: "Hong Kong" },
  { value: "TW", label: "Taiwan" },
  { value: "TH", label: "Thailand" },
  { value: "MY", label: "Malaysia" },
  { value: "ID", label: "Indonesia" },
  { value: "PH", label: "Philippines" },
  { value: "VN", label: "Vietnam" },
  { value: "BR", label: "Brazil" },
  { value: "MX", label: "Mexico" },
  { value: "AR", label: "Argentina" },
  { value: "CL", label: "Chile" },
  { value: "CO", label: "Colombia" },
  { value: "PE", label: "Peru" },
  { value: "ZA", label: "South Africa" },
  { value: "EG", label: "Egypt" },
  { value: "NG", label: "Nigeria" },
  { value: "KE", label: "Kenya" },
  { value: "MA", label: "Morocco" },
  { value: "IL", label: "Israel" },
  { value: "AE", label: "United Arab Emirates" },
  { value: "SA", label: "Saudi Arabia" },
  { value: "TR", label: "Turkey" },
  { value: "RU", label: "Russia" },
  { value: "UA", label: "Ukraine" },
  { value: "PL", label: "Poland" },
  { value: "CZ", label: "Czech Republic" },
  { value: "HU", label: "Hungary" },
  { value: "RO", label: "Romania" },
  { value: "BG", label: "Bulgaria" },
  { value: "HR", label: "Croatia" },
  { value: "SI", label: "Slovenia" },
  { value: "SK", label: "Slovakia" },
  { value: "LT", label: "Lithuania" },
  { value: "LV", label: "Latvia" },
  { value: "EE", label: "Estonia" },
  { value: "IE", label: "Ireland" },
  { value: "PT", label: "Portugal" },
  { value: "GR", label: "Greece" },
  { value: "CY", label: "Cyprus" },
  { value: "MT", label: "Malta" },
  { value: "LU", label: "Luxembourg" },
  { value: "IS", label: "Iceland" },
  { value: "NZ", label: "New Zealand" }
]

// Timezone options with common timezones
export const timezoneOptions: SelectOption[] = [
  // North America
  { value: "America/New_York", label: "Eastern Time (ET)" },
  { value: "America/Chicago", label: "Central Time (CT)" },
  { value: "America/Denver", label: "Mountain Time (MT)" },
  { value: "America/Los_Angeles", label: "Pacific Time (PT)" },
  { value: "America/Anchorage", label: "Alaska Time (AKT)" },
  { value: "Pacific/Honolulu", label: "Hawaii Time (HST)" },
  { value: "America/Toronto", label: "Eastern Time - Toronto" },
  { value: "America/Vancouver", label: "Pacific Time - Vancouver" },
  { value: "America/Mexico_City", label: "Central Time - Mexico City" },
  
  // Europe
  { value: "Europe/London", label: "Greenwich Mean Time (GMT)" },
  { value: "Europe/Paris", label: "Central European Time (CET)" },
  { value: "Europe/Berlin", label: "Central European Time - Berlin" },
  { value: "Europe/Rome", label: "Central European Time - Rome" },
  { value: "Europe/Madrid", label: "Central European Time - Madrid" },
  { value: "Europe/Amsterdam", label: "Central European Time - Amsterdam" },
  { value: "Europe/Brussels", label: "Central European Time - Brussels" },
  { value: "Europe/Zurich", label: "Central European Time - Zurich" },
  { value: "Europe/Vienna", label: "Central European Time - Vienna" },
  { value: "Europe/Stockholm", label: "Central European Time - Stockholm" },
  { value: "Europe/Oslo", label: "Central European Time - Oslo" },
  { value: "Europe/Copenhagen", label: "Central European Time - Copenhagen" },
  { value: "Europe/Helsinki", label: "Eastern European Time - Helsinki" },
  { value: "Europe/Warsaw", label: "Central European Time - Warsaw" },
  { value: "Europe/Prague", label: "Central European Time - Prague" },
  { value: "Europe/Budapest", label: "Central European Time - Budapest" },
  { value: "Europe/Bucharest", label: "Eastern European Time - Bucharest" },
  { value: "Europe/Athens", label: "Eastern European Time - Athens" },
  { value: "Europe/Istanbul", label: "Turkey Time (TRT)" },
  { value: "Europe/Moscow", label: "Moscow Standard Time (MSK)" },
  
  // Asia Pacific
  { value: "Asia/Tokyo", label: "Japan Standard Time (JST)" },
  { value: "Asia/Seoul", label: "Korea Standard Time (KST)" },
  { value: "Asia/Shanghai", label: "China Standard Time (CST)" },
  { value: "Asia/Hong_Kong", label: "Hong Kong Time (HKT)" },
  { value: "Asia/Taipei", label: "Taipei Standard Time (TST)" },
  { value: "Asia/Singapore", label: "Singapore Standard Time (SGT)" },
  { value: "Asia/Bangkok", label: "Indochina Time (ICT)" },
  { value: "Asia/Kuala_Lumpur", label: "Malaysia Time (MYT)" },
  { value: "Asia/Jakarta", label: "Western Indonesia Time (WIB)" },
  { value: "Asia/Manila", label: "Philippine Standard Time (PST)" },
  { value: "Asia/Ho_Chi_Minh", label: "Indochina Time - Ho Chi Minh" },
  { value: "Asia/Kolkata", label: "India Standard Time (IST)" },
  { value: "Asia/Dubai", label: "Gulf Standard Time (GST)" },
  { value: "Asia/Riyadh", label: "Arabia Standard Time (AST)" },
  { value: "Asia/Tel_Aviv", label: "Israel Standard Time (IST)" },
  
  // Australia & Oceania
  { value: "Australia/Sydney", label: "Australian Eastern Time (AET)" },
  { value: "Australia/Melbourne", label: "Australian Eastern Time - Melbourne" },
  { value: "Australia/Brisbane", label: "Australian Eastern Time - Brisbane" },
  { value: "Australia/Perth", label: "Australian Western Time (AWT)" },
  { value: "Australia/Adelaide", label: "Australian Central Time (ACT)" },
  { value: "Australia/Darwin", label: "Australian Central Time - Darwin" },
  { value: "Pacific/Auckland", label: "New Zealand Standard Time (NZST)" },
  
  // South America
  { value: "America/Sao_Paulo", label: "Brasília Time (BRT)" },
  { value: "America/Argentina/Buenos_Aires", label: "Argentina Time (ART)" },
  { value: "America/Santiago", label: "Chile Standard Time (CLT)" },
  { value: "America/Bogota", label: "Colombia Time (COT)" },
  { value: "America/Lima", label: "Peru Time (PET)" },
  
  // Africa
  { value: "Africa/Johannesburg", label: "South Africa Standard Time (SAST)" },
  { value: "Africa/Cairo", label: "Eastern European Time - Cairo" },
  { value: "Africa/Lagos", label: "West Africa Time (WAT)" },
  { value: "Africa/Nairobi", label: "East Africa Time (EAT)" },
  { value: "Africa/Casablanca", label: "Western European Time - Casablanca" }
]

// Language options with locale codes
export const languageOptions: SelectOption[] = [
  { value: "en-US", label: "English (US)" },
  { value: "en-GB", label: "English (UK)" },
  { value: "en-CA", label: "English (Canada)" },
  { value: "en-AU", label: "English (Australia)" },
  { value: "es-ES", label: "Spanish (Spain)" },
  { value: "es-MX", label: "Spanish (Mexico)" },
  { value: "es-AR", label: "Spanish (Argentina)" },
  { value: "fr-FR", label: "French (France)" },
  { value: "fr-CA", label: "French (Canada)" },
  { value: "de-DE", label: "German (Germany)" },
  { value: "de-AT", label: "German (Austria)" },
  { value: "de-CH", label: "German (Switzerland)" },
  { value: "it-IT", label: "Italian (Italy)" },
  { value: "pt-BR", label: "Portuguese (Brazil)" },
  { value: "pt-PT", label: "Portuguese (Portugal)" },
  { value: "nl-NL", label: "Dutch (Netherlands)" },
  { value: "nl-BE", label: "Dutch (Belgium)" },
  { value: "sv-SE", label: "Swedish (Sweden)" },
  { value: "no-NO", label: "Norwegian (Norway)" },
  { value: "da-DK", label: "Danish (Denmark)" },
  { value: "fi-FI", label: "Finnish (Finland)" },
  { value: "pl-PL", label: "Polish (Poland)" },
  { value: "cs-CZ", label: "Czech (Czech Republic)" },
  { value: "hu-HU", label: "Hungarian (Hungary)" },
  { value: "ro-RO", label: "Romanian (Romania)" },
  { value: "bg-BG", label: "Bulgarian (Bulgaria)" },
  { value: "hr-HR", label: "Croatian (Croatia)" },
  { value: "sl-SI", label: "Slovenian (Slovenia)" },
  { value: "sk-SK", label: "Slovak (Slovakia)" },
  { value: "lt-LT", label: "Lithuanian (Lithuania)" },
  { value: "lv-LV", label: "Latvian (Latvia)" },
  { value: "et-EE", label: "Estonian (Estonia)" },
  { value: "el-GR", label: "Greek (Greece)" },
  { value: "tr-TR", label: "Turkish (Turkey)" },
  { value: "ru-RU", label: "Russian (Russia)" },
  { value: "uk-UA", label: "Ukrainian (Ukraine)" },
  { value: "ja-JP", label: "Japanese (Japan)" },
  { value: "ko-KR", label: "Korean (South Korea)" },
  { value: "zh-CN", label: "Chinese (Simplified)" },
  { value: "zh-TW", label: "Chinese (Traditional)" },
  { value: "zh-HK", label: "Chinese (Hong Kong)" },
  { value: "hi-IN", label: "Hindi (India)" },
  { value: "th-TH", label: "Thai (Thailand)" },
  { value: "vi-VN", label: "Vietnamese (Vietnam)" },
  { value: "ms-MY", label: "Malay (Malaysia)" },
  { value: "id-ID", label: "Indonesian (Indonesia)" },
  { value: "tl-PH", label: "Filipino (Philippines)" },
  { value: "ar-SA", label: "Arabic (Saudi Arabia)" },
  { value: "ar-EG", label: "Arabic (Egypt)" },
  { value: "he-IL", label: "Hebrew (Israel)" },
  { value: "fa-IR", label: "Persian (Iran)" },
  { value: "ur-PK", label: "Urdu (Pakistan)" },
  { value: "bn-BD", label: "Bengali (Bangladesh)" },
  { value: "ta-IN", label: "Tamil (India)" },
  { value: "te-IN", label: "Telugu (India)" },
  { value: "ml-IN", label: "Malayalam (India)" },
  { value: "kn-IN", label: "Kannada (India)" },
  { value: "gu-IN", label: "Gujarati (India)" },
  { value: "mr-IN", label: "Marathi (India)" },
  { value: "pa-IN", label: "Punjabi (India)" },
  { value: "sw-KE", label: "Swahili (Kenya)" },
  { value: "am-ET", label: "Amharic (Ethiopia)" },
  { value: "zu-ZA", label: "Zulu (South Africa)" },
  { value: "af-ZA", label: "Afrikaans (South Africa)" }
]
