export interface CountryCode {
  code: string
  code3: string
  dial: string
  name: string
  flag: string
}

export const COUNTRY_CODES: CountryCode[] = [
  { code: 'AF', code3: 'AFG', dial: '+93', name: 'Afghanistan', flag: '\u{1F1E6}\u{1F1EB}' },
  { code: 'AL', code3: 'ALB', dial: '+355', name: 'Albania', flag: '\u{1F1E6}\u{1F1F1}' },
  { code: 'DZ', code3: 'DZA', dial: '+213', name: 'Algeria', flag: '\u{1F1E9}\u{1F1FF}' },
  { code: 'AD', code3: 'AND', dial: '+376', name: 'Andorra', flag: '\u{1F1E6}\u{1F1E9}' },
  { code: 'AO', code3: 'AGO', dial: '+244', name: 'Angola', flag: '\u{1F1E6}\u{1F1F4}' },
  { code: 'AG', code3: 'ATG', dial: '+1', name: 'Antigua and Barbuda', flag: '\u{1F1E6}\u{1F1EC}' },
  { code: 'AR', code3: 'ARG', dial: '+54', name: 'Argentina', flag: '\u{1F1E6}\u{1F1F7}' },
  { code: 'AM', code3: 'ARM', dial: '+374', name: 'Armenia', flag: '\u{1F1E6}\u{1F1F2}' },
  { code: 'AU', code3: 'AUS', dial: '+61', name: 'Australia', flag: '\u{1F1E6}\u{1F1FA}' },
  { code: 'AT', code3: 'AUT', dial: '+43', name: 'Austria', flag: '\u{1F1E6}\u{1F1F9}' },
  { code: 'AZ', code3: 'AZE', dial: '+994', name: 'Azerbaijan', flag: '\u{1F1E6}\u{1F1FF}' },
  { code: 'BS', code3: 'BHS', dial: '+1', name: 'Bahamas', flag: '\u{1F1E7}\u{1F1F8}' },
  { code: 'BH', code3: 'BHR', dial: '+973', name: 'Bahrain', flag: '\u{1F1E7}\u{1F1ED}' },
  { code: 'BD', code3: 'BGD', dial: '+880', name: 'Bangladesh', flag: '\u{1F1E7}\u{1F1E9}' },
  { code: 'BB', code3: 'BRB', dial: '+1', name: 'Barbados', flag: '\u{1F1E7}\u{1F1E7}' },
  { code: 'BY', code3: 'BLR', dial: '+375', name: 'Belarus', flag: '\u{1F1E7}\u{1F1FE}' },
  { code: 'BE', code3: 'BEL', dial: '+32', name: 'Belgium', flag: '\u{1F1E7}\u{1F1EA}' },
  { code: 'BZ', code3: 'BLZ', dial: '+501', name: 'Belize', flag: '\u{1F1E7}\u{1F1FF}' },
  { code: 'BJ', code3: 'BEN', dial: '+229', name: 'Benin', flag: '\u{1F1E7}\u{1F1EF}' },
  { code: 'BT', code3: 'BTN', dial: '+975', name: 'Bhutan', flag: '\u{1F1E7}\u{1F1F9}' },
  { code: 'BO', code3: 'BOL', dial: '+591', name: 'Bolivia', flag: '\u{1F1E7}\u{1F1F4}' },
  { code: 'BA', code3: 'BIH', dial: '+387', name: 'Bosnia and Herzegovina', flag: '\u{1F1E7}\u{1F1E6}' },
  { code: 'BW', code3: 'BWA', dial: '+267', name: 'Botswana', flag: '\u{1F1E7}\u{1F1FC}' },
  { code: 'BR', code3: 'BRA', dial: '+55', name: 'Brazil', flag: '\u{1F1E7}\u{1F1F7}' },
  { code: 'BN', code3: 'BRN', dial: '+673', name: 'Brunei', flag: '\u{1F1E7}\u{1F1F3}' },
  { code: 'BG', code3: 'BGR', dial: '+359', name: 'Bulgaria', flag: '\u{1F1E7}\u{1F1EC}' },
  { code: 'BF', code3: 'BFA', dial: '+226', name: 'Burkina Faso', flag: '\u{1F1E7}\u{1F1EB}' },
  { code: 'BI', code3: 'BDI', dial: '+257', name: 'Burundi', flag: '\u{1F1E7}\u{1F1EE}' },
  { code: 'CV', code3: 'CPV', dial: '+238', name: 'Cabo Verde', flag: '\u{1F1E8}\u{1F1FB}' },
  { code: 'KH', code3: 'KHM', dial: '+855', name: 'Cambodia', flag: '\u{1F1F0}\u{1F1ED}' },
  { code: 'CM', code3: 'CMR', dial: '+237', name: 'Cameroon', flag: '\u{1F1E8}\u{1F1F2}' },
  { code: 'CA', code3: 'CAN', dial: '+1', name: 'Canada', flag: '\u{1F1E8}\u{1F1E6}' },
  { code: 'CF', code3: 'CAF', dial: '+236', name: 'Central African Republic', flag: '\u{1F1E8}\u{1F1EB}' },
  { code: 'TD', code3: 'TCD', dial: '+235', name: 'Chad', flag: '\u{1F1F9}\u{1F1E9}' },
  { code: 'CL', code3: 'CHL', dial: '+56', name: 'Chile', flag: '\u{1F1E8}\u{1F1F1}' },
  { code: 'CN', code3: 'CHN', dial: '+86', name: 'China', flag: '\u{1F1E8}\u{1F1F3}' },
  { code: 'CO', code3: 'COL', dial: '+57', name: 'Colombia', flag: '\u{1F1E8}\u{1F1F4}' },
  { code: 'KM', code3: 'COM', dial: '+269', name: 'Comoros', flag: '\u{1F1F0}\u{1F1F2}' },
  { code: 'CG', code3: 'COG', dial: '+242', name: 'Congo', flag: '\u{1F1E8}\u{1F1EC}' },
  { code: 'CD', code3: 'COD', dial: '+243', name: 'Congo (DRC)', flag: '\u{1F1E8}\u{1F1E9}' },
  { code: 'CR', code3: 'CRI', dial: '+506', name: 'Costa Rica', flag: '\u{1F1E8}\u{1F1F7}' },
  { code: 'CI', code3: 'CIV', dial: '+225', name: "C\u00f4te d'Ivoire", flag: '\u{1F1E8}\u{1F1EE}' },
  { code: 'HR', code3: 'HRV', dial: '+385', name: 'Croatia', flag: '\u{1F1ED}\u{1F1F7}' },
  { code: 'CU', code3: 'CUB', dial: '+53', name: 'Cuba', flag: '\u{1F1E8}\u{1F1FA}' },
  { code: 'CY', code3: 'CYP', dial: '+357', name: 'Cyprus', flag: '\u{1F1E8}\u{1F1FE}' },
  { code: 'CZ', code3: 'CZE', dial: '+420', name: 'Czech Republic', flag: '\u{1F1E8}\u{1F1FF}' },
  { code: 'DK', code3: 'DNK', dial: '+45', name: 'Denmark', flag: '\u{1F1E9}\u{1F1F0}' },
  { code: 'DJ', code3: 'DJI', dial: '+253', name: 'Djibouti', flag: '\u{1F1E9}\u{1F1EF}' },
  { code: 'DM', code3: 'DMA', dial: '+1', name: 'Dominica', flag: '\u{1F1E9}\u{1F1F2}' },
  { code: 'DO', code3: 'DOM', dial: '+1', name: 'Dominican Republic', flag: '\u{1F1E9}\u{1F1F4}' },
  { code: 'EC', code3: 'ECU', dial: '+593', name: 'Ecuador', flag: '\u{1F1EA}\u{1F1E8}' },
  { code: 'EG', code3: 'EGY', dial: '+20', name: 'Egypt', flag: '\u{1F1EA}\u{1F1EC}' },
  { code: 'SV', code3: 'SLV', dial: '+503', name: 'El Salvador', flag: '\u{1F1F8}\u{1F1FB}' },
  { code: 'GQ', code3: 'GNQ', dial: '+240', name: 'Equatorial Guinea', flag: '\u{1F1EC}\u{1F1F6}' },
  { code: 'ER', code3: 'ERI', dial: '+291', name: 'Eritrea', flag: '\u{1F1EA}\u{1F1F7}' },
  { code: 'EE', code3: 'EST', dial: '+372', name: 'Estonia', flag: '\u{1F1EA}\u{1F1EA}' },
  { code: 'SZ', code3: 'SWZ', dial: '+268', name: 'Eswatini', flag: '\u{1F1F8}\u{1F1FF}' },
  { code: 'ET', code3: 'ETH', dial: '+251', name: 'Ethiopia', flag: '\u{1F1EA}\u{1F1F9}' },
  { code: 'FJ', code3: 'FJI', dial: '+679', name: 'Fiji', flag: '\u{1F1EB}\u{1F1EF}' },
  { code: 'FI', code3: 'FIN', dial: '+358', name: 'Finland', flag: '\u{1F1EB}\u{1F1EE}' },
  { code: 'FR', code3: 'FRA', dial: '+33', name: 'France', flag: '\u{1F1EB}\u{1F1F7}' },
  { code: 'GA', code3: 'GAB', dial: '+241', name: 'Gabon', flag: '\u{1F1EC}\u{1F1E6}' },
  { code: 'GM', code3: 'GMB', dial: '+220', name: 'Gambia', flag: '\u{1F1EC}\u{1F1F2}' },
  { code: 'GE', code3: 'GEO', dial: '+995', name: 'Georgia', flag: '\u{1F1EC}\u{1F1EA}' },
  { code: 'DE', code3: 'DEU', dial: '+49', name: 'Germany', flag: '\u{1F1E9}\u{1F1EA}' },
  { code: 'GH', code3: 'GHA', dial: '+233', name: 'Ghana', flag: '\u{1F1EC}\u{1F1ED}' },
  { code: 'GR', code3: 'GRC', dial: '+30', name: 'Greece', flag: '\u{1F1EC}\u{1F1F7}' },
  { code: 'GD', code3: 'GRD', dial: '+1', name: 'Grenada', flag: '\u{1F1EC}\u{1F1E9}' },
  { code: 'GT', code3: 'GTM', dial: '+502', name: 'Guatemala', flag: '\u{1F1EC}\u{1F1F9}' },
  { code: 'GN', code3: 'GIN', dial: '+224', name: 'Guinea', flag: '\u{1F1EC}\u{1F1F3}' },
  { code: 'GW', code3: 'GNB', dial: '+245', name: 'Guinea-Bissau', flag: '\u{1F1EC}\u{1F1FC}' },
  { code: 'GY', code3: 'GUY', dial: '+592', name: 'Guyana', flag: '\u{1F1EC}\u{1F1FE}' },
  { code: 'HT', code3: 'HTI', dial: '+509', name: 'Haiti', flag: '\u{1F1ED}\u{1F1F9}' },
  { code: 'HN', code3: 'HND', dial: '+504', name: 'Honduras', flag: '\u{1F1ED}\u{1F1F3}' },
  { code: 'HK', code3: 'HKG', dial: '+852', name: 'Hong Kong', flag: '\u{1F1ED}\u{1F1F0}' },
  { code: 'HU', code3: 'HUN', dial: '+36', name: 'Hungary', flag: '\u{1F1ED}\u{1F1FA}' },
  { code: 'IS', code3: 'ISL', dial: '+354', name: 'Iceland', flag: '\u{1F1EE}\u{1F1F8}' },
  { code: 'IN', code3: 'IND', dial: '+91', name: 'India', flag: '\u{1F1EE}\u{1F1F3}' },
  { code: 'ID', code3: 'IDN', dial: '+62', name: 'Indonesia', flag: '\u{1F1EE}\u{1F1E9}' },
  { code: 'IR', code3: 'IRN', dial: '+98', name: 'Iran', flag: '\u{1F1EE}\u{1F1F7}' },
  { code: 'IQ', code3: 'IRQ', dial: '+964', name: 'Iraq', flag: '\u{1F1EE}\u{1F1F6}' },
  { code: 'IE', code3: 'IRL', dial: '+353', name: 'Ireland', flag: '\u{1F1EE}\u{1F1EA}' },
  { code: 'IL', code3: 'ISR', dial: '+972', name: 'Israel', flag: '\u{1F1EE}\u{1F1F1}' },
  { code: 'IT', code3: 'ITA', dial: '+39', name: 'Italy', flag: '\u{1F1EE}\u{1F1F9}' },
  { code: 'JM', code3: 'JAM', dial: '+1', name: 'Jamaica', flag: '\u{1F1EF}\u{1F1F2}' },
  { code: 'JP', code3: 'JPN', dial: '+81', name: 'Japan', flag: '\u{1F1EF}\u{1F1F5}' },
  { code: 'JO', code3: 'JOR', dial: '+962', name: 'Jordan', flag: '\u{1F1EF}\u{1F1F4}' },
  { code: 'KZ', code3: 'KAZ', dial: '+7', name: 'Kazakhstan', flag: '\u{1F1F0}\u{1F1FF}' },
  { code: 'KE', code3: 'KEN', dial: '+254', name: 'Kenya', flag: '\u{1F1F0}\u{1F1EA}' },
  { code: 'KI', code3: 'KIR', dial: '+686', name: 'Kiribati', flag: '\u{1F1F0}\u{1F1EE}' },
  { code: 'KW', code3: 'KWT', dial: '+965', name: 'Kuwait', flag: '\u{1F1F0}\u{1F1FC}' },
  { code: 'KG', code3: 'KGZ', dial: '+996', name: 'Kyrgyzstan', flag: '\u{1F1F0}\u{1F1EC}' },
  { code: 'LA', code3: 'LAO', dial: '+856', name: 'Laos', flag: '\u{1F1F1}\u{1F1E6}' },
  { code: 'LV', code3: 'LVA', dial: '+371', name: 'Latvia', flag: '\u{1F1F1}\u{1F1FB}' },
  { code: 'LB', code3: 'LBN', dial: '+961', name: 'Lebanon', flag: '\u{1F1F1}\u{1F1E7}' },
  { code: 'LS', code3: 'LSO', dial: '+266', name: 'Lesotho', flag: '\u{1F1F1}\u{1F1F8}' },
  { code: 'LR', code3: 'LBR', dial: '+231', name: 'Liberia', flag: '\u{1F1F1}\u{1F1F7}' },
  { code: 'LY', code3: 'LBY', dial: '+218', name: 'Libya', flag: '\u{1F1F1}\u{1F1FE}' },
  { code: 'LI', code3: 'LIE', dial: '+423', name: 'Liechtenstein', flag: '\u{1F1F1}\u{1F1EE}' },
  { code: 'LT', code3: 'LTU', dial: '+370', name: 'Lithuania', flag: '\u{1F1F1}\u{1F1F9}' },
  { code: 'LU', code3: 'LUX', dial: '+352', name: 'Luxembourg', flag: '\u{1F1F1}\u{1F1FA}' },
  { code: 'MO', code3: 'MAC', dial: '+853', name: 'Macau', flag: '\u{1F1F2}\u{1F1F4}' },
  { code: 'MG', code3: 'MDG', dial: '+261', name: 'Madagascar', flag: '\u{1F1F2}\u{1F1EC}' },
  { code: 'MW', code3: 'MWI', dial: '+265', name: 'Malawi', flag: '\u{1F1F2}\u{1F1FC}' },
  { code: 'MY', code3: 'MYS', dial: '+60', name: 'Malaysia', flag: '\u{1F1F2}\u{1F1FE}' },
  { code: 'MV', code3: 'MDV', dial: '+960', name: 'Maldives', flag: '\u{1F1F2}\u{1F1FB}' },
  { code: 'ML', code3: 'MLI', dial: '+223', name: 'Mali', flag: '\u{1F1F2}\u{1F1F1}' },
  { code: 'MT', code3: 'MLT', dial: '+356', name: 'Malta', flag: '\u{1F1F2}\u{1F1F9}' },
  { code: 'MH', code3: 'MHL', dial: '+692', name: 'Marshall Islands', flag: '\u{1F1F2}\u{1F1ED}' },
  { code: 'MR', code3: 'MRT', dial: '+222', name: 'Mauritania', flag: '\u{1F1F2}\u{1F1F7}' },
  { code: 'MU', code3: 'MUS', dial: '+230', name: 'Mauritius', flag: '\u{1F1F2}\u{1F1FA}' },
  { code: 'MX', code3: 'MEX', dial: '+52', name: 'Mexico', flag: '\u{1F1F2}\u{1F1FD}' },
  { code: 'FM', code3: 'FSM', dial: '+691', name: 'Micronesia', flag: '\u{1F1EB}\u{1F1F2}' },
  { code: 'MD', code3: 'MDA', dial: '+373', name: 'Moldova', flag: '\u{1F1F2}\u{1F1E9}' },
  { code: 'MC', code3: 'MCO', dial: '+377', name: 'Monaco', flag: '\u{1F1F2}\u{1F1E8}' },
  { code: 'MN', code3: 'MNG', dial: '+976', name: 'Mongolia', flag: '\u{1F1F2}\u{1F1F3}' },
  { code: 'ME', code3: 'MNE', dial: '+382', name: 'Montenegro', flag: '\u{1F1F2}\u{1F1EA}' },
  { code: 'MA', code3: 'MAR', dial: '+212', name: 'Morocco', flag: '\u{1F1F2}\u{1F1E6}' },
  { code: 'MZ', code3: 'MOZ', dial: '+258', name: 'Mozambique', flag: '\u{1F1F2}\u{1F1FF}' },
  { code: 'MM', code3: 'MMR', dial: '+95', name: 'Myanmar', flag: '\u{1F1F2}\u{1F1F2}' },
  { code: 'NA', code3: 'NAM', dial: '+264', name: 'Namibia', flag: '\u{1F1F3}\u{1F1E6}' },
  { code: 'NR', code3: 'NRU', dial: '+674', name: 'Nauru', flag: '\u{1F1F3}\u{1F1F7}' },
  { code: 'NP', code3: 'NPL', dial: '+977', name: 'Nepal', flag: '\u{1F1F3}\u{1F1F5}' },
  { code: 'NL', code3: 'NLD', dial: '+31', name: 'Netherlands', flag: '\u{1F1F3}\u{1F1F1}' },
  { code: 'NZ', code3: 'NZL', dial: '+64', name: 'New Zealand', flag: '\u{1F1F3}\u{1F1FF}' },
  { code: 'NI', code3: 'NIC', dial: '+505', name: 'Nicaragua', flag: '\u{1F1F3}\u{1F1EE}' },
  { code: 'NE', code3: 'NER', dial: '+227', name: 'Niger', flag: '\u{1F1F3}\u{1F1EA}' },
  { code: 'NG', code3: 'NGA', dial: '+234', name: 'Nigeria', flag: '\u{1F1F3}\u{1F1EC}' },
  { code: 'KP', code3: 'PRK', dial: '+850', name: 'North Korea', flag: '\u{1F1F0}\u{1F1F5}' },
  { code: 'MK', code3: 'MKD', dial: '+389', name: 'North Macedonia', flag: '\u{1F1F2}\u{1F1F0}' },
  { code: 'NO', code3: 'NOR', dial: '+47', name: 'Norway', flag: '\u{1F1F3}\u{1F1F4}' },
  { code: 'OM', code3: 'OMN', dial: '+968', name: 'Oman', flag: '\u{1F1F4}\u{1F1F2}' },
  { code: 'PK', code3: 'PAK', dial: '+92', name: 'Pakistan', flag: '\u{1F1F5}\u{1F1F0}' },
  { code: 'PW', code3: 'PLW', dial: '+680', name: 'Palau', flag: '\u{1F1F5}\u{1F1FC}' },
  { code: 'PS', code3: 'PSE', dial: '+970', name: 'Palestine', flag: '\u{1F1F5}\u{1F1F8}' },
  { code: 'PA', code3: 'PAN', dial: '+507', name: 'Panama', flag: '\u{1F1F5}\u{1F1E6}' },
  { code: 'PG', code3: 'PNG', dial: '+675', name: 'Papua New Guinea', flag: '\u{1F1F5}\u{1F1EC}' },
  { code: 'PY', code3: 'PRY', dial: '+595', name: 'Paraguay', flag: '\u{1F1F5}\u{1F1FE}' },
  { code: 'PE', code3: 'PER', dial: '+51', name: 'Peru', flag: '\u{1F1F5}\u{1F1EA}' },
  { code: 'PH', code3: 'PHL', dial: '+63', name: 'Philippines', flag: '\u{1F1F5}\u{1F1ED}' },
  { code: 'PL', code3: 'POL', dial: '+48', name: 'Poland', flag: '\u{1F1F5}\u{1F1F1}' },
  { code: 'PT', code3: 'PRT', dial: '+351', name: 'Portugal', flag: '\u{1F1F5}\u{1F1F9}' },
  { code: 'PR', code3: 'PRI', dial: '+1', name: 'Puerto Rico', flag: '\u{1F1F5}\u{1F1F7}' },
  { code: 'QA', code3: 'QAT', dial: '+974', name: 'Qatar', flag: '\u{1F1F6}\u{1F1E6}' },
  { code: 'RO', code3: 'ROU', dial: '+40', name: 'Romania', flag: '\u{1F1F7}\u{1F1F4}' },
  { code: 'RU', code3: 'RUS', dial: '+7', name: 'Russia', flag: '\u{1F1F7}\u{1F1FA}' },
  { code: 'RW', code3: 'RWA', dial: '+250', name: 'Rwanda', flag: '\u{1F1F7}\u{1F1FC}' },
  { code: 'KN', code3: 'KNA', dial: '+1', name: 'Saint Kitts and Nevis', flag: '\u{1F1F0}\u{1F1F3}' },
  { code: 'LC', code3: 'LCA', dial: '+1', name: 'Saint Lucia', flag: '\u{1F1F1}\u{1F1E8}' },
  { code: 'VC', code3: 'VCT', dial: '+1', name: 'Saint Vincent and the Grenadines', flag: '\u{1F1FB}\u{1F1E6}' },
  { code: 'WS', code3: 'WSM', dial: '+685', name: 'Samoa', flag: '\u{1F1FC}\u{1F1F8}' },
  { code: 'SM', code3: 'SMR', dial: '+378', name: 'San Marino', flag: '\u{1F1F8}\u{1F1F2}' },
  { code: 'ST', code3: 'STP', dial: '+239', name: 'S\u00e3o Tom\u00e9 and Pr\u00edncipe', flag: '\u{1F1F8}\u{1F1F9}' },
  { code: 'SA', code3: 'SAU', dial: '+966', name: 'Saudi Arabia', flag: '\u{1F1F8}\u{1F1E6}' },
  { code: 'SN', code3: 'SEN', dial: '+221', name: 'Senegal', flag: '\u{1F1F8}\u{1F1F3}' },
  { code: 'RS', code3: 'SRB', dial: '+381', name: 'Serbia', flag: '\u{1F1F7}\u{1F1F8}' },
  { code: 'SC', code3: 'SYC', dial: '+248', name: 'Seychelles', flag: '\u{1F1F8}\u{1F1E8}' },
  { code: 'SL', code3: 'SLE', dial: '+232', name: 'Sierra Leone', flag: '\u{1F1F8}\u{1F1F1}' },
  { code: 'SG', code3: 'SGP', dial: '+65', name: 'Singapore', flag: '\u{1F1F8}\u{1F1EC}' },
  { code: 'SK', code3: 'SVK', dial: '+421', name: 'Slovakia', flag: '\u{1F1F8}\u{1F1F0}' },
  { code: 'SI', code3: 'SVN', dial: '+386', name: 'Slovenia', flag: '\u{1F1F8}\u{1F1EE}' },
  { code: 'SB', code3: 'SLB', dial: '+677', name: 'Solomon Islands', flag: '\u{1F1F8}\u{1F1E7}' },
  { code: 'SO', code3: 'SOM', dial: '+252', name: 'Somalia', flag: '\u{1F1F8}\u{1F1F4}' },
  { code: 'ZA', code3: 'ZAF', dial: '+27', name: 'South Africa', flag: '\u{1F1FF}\u{1F1E6}' },
  { code: 'KR', code3: 'KOR', dial: '+82', name: 'South Korea', flag: '\u{1F1F0}\u{1F1F7}' },
  { code: 'SS', code3: 'SSD', dial: '+211', name: 'South Sudan', flag: '\u{1F1F8}\u{1F1F8}' },
  { code: 'ES', code3: 'ESP', dial: '+34', name: 'Spain', flag: '\u{1F1EA}\u{1F1F8}' },
  { code: 'LK', code3: 'LKA', dial: '+94', name: 'Sri Lanka', flag: '\u{1F1F1}\u{1F1F0}' },
  { code: 'SD', code3: 'SDN', dial: '+249', name: 'Sudan', flag: '\u{1F1F8}\u{1F1E9}' },
  { code: 'SR', code3: 'SUR', dial: '+597', name: 'Suriname', flag: '\u{1F1F8}\u{1F1F7}' },
  { code: 'SE', code3: 'SWE', dial: '+46', name: 'Sweden', flag: '\u{1F1F8}\u{1F1EA}' },
  { code: 'CH', code3: 'CHE', dial: '+41', name: 'Switzerland', flag: '\u{1F1E8}\u{1F1ED}' },
  { code: 'SY', code3: 'SYR', dial: '+963', name: 'Syria', flag: '\u{1F1F8}\u{1F1FE}' },
  { code: 'TW', code3: 'TWN', dial: '+886', name: 'Taiwan', flag: '\u{1F1F9}\u{1F1FC}' },
  { code: 'TJ', code3: 'TJK', dial: '+992', name: 'Tajikistan', flag: '\u{1F1F9}\u{1F1EF}' },
  { code: 'TZ', code3: 'TZA', dial: '+255', name: 'Tanzania', flag: '\u{1F1F9}\u{1F1FF}' },
  { code: 'TH', code3: 'THA', dial: '+66', name: 'Thailand', flag: '\u{1F1F9}\u{1F1ED}' },
  { code: 'TL', code3: 'TLS', dial: '+670', name: 'Timor-Leste', flag: '\u{1F1F9}\u{1F1F1}' },
  { code: 'TG', code3: 'TGO', dial: '+228', name: 'Togo', flag: '\u{1F1F9}\u{1F1EC}' },
  { code: 'TO', code3: 'TON', dial: '+676', name: 'Tonga', flag: '\u{1F1F9}\u{1F1F4}' },
  { code: 'TT', code3: 'TTO', dial: '+1', name: 'Trinidad and Tobago', flag: '\u{1F1F9}\u{1F1F9}' },
  { code: 'TN', code3: 'TUN', dial: '+216', name: 'Tunisia', flag: '\u{1F1F9}\u{1F1F3}' },
  { code: 'TR', code3: 'TUR', dial: '+90', name: 'Turkey', flag: '\u{1F1F9}\u{1F1F7}' },
  { code: 'TM', code3: 'TKM', dial: '+993', name: 'Turkmenistan', flag: '\u{1F1F9}\u{1F1F2}' },
  { code: 'TV', code3: 'TUV', dial: '+688', name: 'Tuvalu', flag: '\u{1F1F9}\u{1F1FB}' },
  { code: 'UG', code3: 'UGA', dial: '+256', name: 'Uganda', flag: '\u{1F1FA}\u{1F1EC}' },
  { code: 'UA', code3: 'UKR', dial: '+380', name: 'Ukraine', flag: '\u{1F1FA}\u{1F1E6}' },
  { code: 'AE', code3: 'ARE', dial: '+971', name: 'United Arab Emirates', flag: '\u{1F1E6}\u{1F1EA}' },
  { code: 'GB', code3: 'GBR', dial: '+44', name: 'United Kingdom', flag: '\u{1F1EC}\u{1F1E7}' },
  { code: 'US', code3: 'USA', dial: '+1', name: 'United States', flag: '\u{1F1FA}\u{1F1F8}' },
  { code: 'UY', code3: 'URY', dial: '+598', name: 'Uruguay', flag: '\u{1F1FA}\u{1F1FE}' },
  { code: 'UZ', code3: 'UZB', dial: '+998', name: 'Uzbekistan', flag: '\u{1F1FA}\u{1F1FF}' },
  { code: 'VU', code3: 'VUT', dial: '+678', name: 'Vanuatu', flag: '\u{1F1FB}\u{1F1FA}' },
  { code: 'VA', code3: 'VAT', dial: '+379', name: 'Vatican City', flag: '\u{1F1FB}\u{1F1E6}' },
  { code: 'VE', code3: 'VEN', dial: '+58', name: 'Venezuela', flag: '\u{1F1FB}\u{1F1EA}' },
  { code: 'VN', code3: 'VNM', dial: '+84', name: 'Vietnam', flag: '\u{1F1FB}\u{1F1F3}' },
  { code: 'YE', code3: 'YEM', dial: '+967', name: 'Yemen', flag: '\u{1F1FE}\u{1F1EA}' },
  { code: 'ZM', code3: 'ZMB', dial: '+260', name: 'Zambia', flag: '\u{1F1FF}\u{1F1F2}' },
  { code: 'ZW', code3: 'ZWE', dial: '+263', name: 'Zimbabwe', flag: '\u{1F1FF}\u{1F1FC}' },
]
