import type { Container } from "./components/ContainerColumns"

export const MOCK_CONTAINERS: Container[] = [
  {
    id: "cont_default",
    name: "Default",
    description: "System container for internal users and administrative access",
    domain: "system.auth.example.com",
    status: "active",
    userCount: 25,
    adminCount: 5,
    lastActivity: "2024-01-26T16:50:00Z",
    createdAt: "2024-01-01T00:00:00Z",
    createdBy: "system",
    features: ["SSO", "2FA", "RBAC", "Audit Logs", "System Access"],
    isSystem: true
  },
  {
    id: "cont_1",
    name: "Acme Corporation",
    description: "Main production tenant for Acme Corporation with full feature access",
    domain: "acme.auth.example.com",
    status: "active",
    userCount: 1250,
    adminCount: 8,
    lastActivity: "2024-01-26T14:30:00Z",
    createdAt: "2024-01-15T10:30:00Z",
    createdBy: "admin",
    features: ["SSO", "2FA", "RBAC", "Audit Logs", "Custom Branding"],
    isSystem: false
  },
  {
    id: "cont_2",
    name: "TechStart Inc",
    description: "Startup tenant with basic authentication features",
    domain: "techstart.auth.example.com",
    status: "active",
    userCount: 45,
    adminCount: 2,
    lastActivity: "2024-01-26T16:15:00Z",
    createdAt: "2024-01-08T14:20:00Z",
    createdBy: "admin",
    features: ["SSO", "2FA", "RBAC"],
    isSystem: false
  },
  {
    id: "cont_3",
    name: "Global Retail",
    description: "Multi-region retail chain with complex user hierarchy",
    domain: "retail.auth.example.com",
    status: "active",
    userCount: 3200,
    adminCount: 15,
    lastActivity: "2024-01-26T16:45:00Z",
    createdAt: "2023-12-25T16:45:00Z",
    createdBy: "system",
    features: ["SSO", "2FA", "RBAC", "Audit Logs", "Custom Branding", "API Access"],
    isSystem: false
  },
  {
    id: "cont_4",
    name: "Beta Testing Org",
    description: "Testing environment for new features and integrations",
    domain: "beta.auth.example.com",
    status: "suspended",
    userCount: 12,
    adminCount: 1,
    lastActivity: "2024-01-20T09:30:00Z",
    createdAt: "2024-01-20T11:00:00Z",
    createdBy: "developer",
    features: ["SSO"],
    isSystem: false
  },
  {
    id: "cont_5",
    name: "DevCorp Solutions",
    description: "Development agency managing multiple client projects",
    domain: "devcorp.auth.example.com",
    status: "active",
    userCount: 89,
    adminCount: 4,
    lastActivity: "2024-01-26T12:20:00Z",
    createdAt: "2024-01-22T09:30:00Z",
    createdBy: "admin",
    features: ["SSO", "2FA", "RBAC"],
    isSystem: false
  },
  {
    id: "cont_6",
    name: "Healthcare Plus",
    description: "Healthcare organization with strict compliance requirements",
    domain: "healthcare.auth.example.com",
    status: "active",
    userCount: 850,
    adminCount: 6,
    lastActivity: "2024-01-26T15:10:00Z",
    createdAt: "2023-12-10T08:15:00Z",
    createdBy: "admin",
    features: ["SSO", "2FA", "RBAC", "Audit Logs", "Compliance Reports"],
    isSystem: false
  },
  {
    id: "cont_7",
    name: "Demo Environment",
    description: "Demonstration tenant for sales and marketing purposes",
    domain: "demo.auth.example.com",
    status: "inactive",
    userCount: 5,
    adminCount: 1,
    lastActivity: "2024-01-26T10:45:00Z",
    createdAt: "2024-01-26T10:45:00Z",
    createdBy: "sales",
    features: ["SSO", "2FA"],
    isSystem: false
  }
]
